spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            - id: order
              uri: lb://order-service/order
              predicates:
                - Path= /api/order/**
              filters:
                - StripPrefix= 1
            - id: customer
              uri: lb://customer-service/customer
              predicates:
                - Path= /api/customer/**
              filters:
                - StripPrefix= 1
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8000/eureka}