# ... Namespace YAML definition
apiVersion: v1
kind: Namespace
metadata:
  name: ms
  labels:
    name: ms

---
# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-config
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-config
  template:
    metadata:
      labels:
        app: service-config
    spec:
      containers:
        - name: service-config
          image: co.in.va.ms.api/service_config:0.0.3
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: service-config
  namespace: ms
spec:
  selector:
    app: service-config
  ports:
    - port: 8020
      targetPort: 8020
  type: LoadBalancer